### ISSUE TITLE
Rollup crashes frequently

### ISSUE THREAD

**Issue by mangozila** [astriaorg/astria#648]
After successfully deployed a rollup locally I realize that my rollup crashing continously as the log below

```
root@iZt4ni96r4tp2qzbf1epkoZ:~/astria# kubectl get pods -n astria-dev-cluster -w
NAME                                          READY   STATUS             RESTARTS   AGE
mangozila-local-blockscout-76ff969565-bwwj2   5/6     CrashLoopBackOff   1322       4d17h
mangozila-local-faucet-68df5c8d48-sx87t       1/1     Running            5          4d17h
mangozila-local-geth-5cbc88b5f8-j2xlk         2/3     CrashLoopBackOff   872        4d17h
mangozila-local-blockscout-76ff969565-bwwj2   6/6     Running            1323       4d17h
mangozila-local-blockscout-76ff969565-bwwj2   5/6     Error              1323       4d17h
mangozila-local-blockscout-76ff969565-bwwj2   5/6     CrashLoopBackOff   1323       4d17h
mangozila-local-geth-5cbc88b5f8-j2xlk         3/3     Running            873        4d17h
```
what cause this error ?

**Comment by jbowen93** [comment]
Hey @mangozila thanks for filing a bug, can you provide a little more information to help us debug.

Are you running this rollup locally or on Digital Ocean? 

If locally what operating system are you using? Did you use the steps suggested in the guide which would mean you're running Docker Desktop, with Kubernetes in Docker (kind).

To get more details on the specific rollup failure could you run:
```
kubectl describe po mangozila-local-geth-5cbc88b5f8-j2xlk  -n astria-dev-cluster 
```

This will tell us what container within the pod is failing. There are 3 possibilities:
1. `geth`
2. `composer`
3.  `conductor`

We'll also want to look at the logs of the failing container, you can see this with:
```
kubectl logs mangozila-local-geth-5cbc88b5f8-j2xlk -c <container-name> -n  astria-dev-cluster
```

Replace `<container-name>` with one of `geth`, `composer`, or `conductor`

Could you please post the output of these commands in a comment here, thanks!

**Comment by jbowen93** [comment]
Looking at the timing of the rollup creation, my assumption is that your rollup is running against the older `dusk-1` network as opposed to the newer `dusk-2` network which we [announced on Monday](https://blog.astria.org/astria-dusknet-2/).

We have turned off the `dusk-1` network, but failed to announce our intent to do this and to ensure existing users were informed, that's our mistake and I apologize.

With the transition from `dusk-1` to `dusk-2` we made changes to the underlying data structure of sequencer blocks, unfortunately this means rollups which were deployed to `dusk-1` can't be easily upgraded to use `dusk-2`. 

We recommend redeploying your rollup from scratch following the steps outlined in our [updated docs](https://docs.astria.org/docs/cloud-rollup/digital-ocean/).

You'll also want to make sure you reinstall the `astria-cli` at `v0.2.0` or newer, you can check this by running
```
astria-cli -V
``` 

To validate that your new rollup is using the latest `dusk-2` network ensure that the `config.sequencer.rpc` field in your rollup configuration file is set to `https://rpc.sequencer.dusk-2.devnet.astria.org` as show in our docs.

```
global:
  namespace: astria-dev-cluster
  useTTY: false
  logLevel: debug
config:
  rollup:
    name: <YOUR_ROLLUP_NAME>
    chainId: <YOUR_ROLLUP_NAME>-chain
    networkId: '<YOUR_NETWORK_ID>'
    genesisAccounts:
    - address: <GENESIS_ADDRESS>
      balance: '<BALANCE>'
  sequencer:
    initialBlockHeight: <INITIAL_SEQUENCER_BLOCK_HEIGHT>
    websocket: wss://rpc.sequencer.dusk-2.devnet.astria.org/websocket
    rpc: https://rpc.sequencer.dusk-2.devnet.astria.org
ingress:
  hostname: <YOUR_HOSTNAME>
celestia-node:
  config:
    labelPrefix: <YOUR_ROLLUP_NAME>
```
